//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odes.License.Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odes.License.Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22,96,234,173,144,94,243,213,67,101,231,245,28,219,64,96,98,183,244,148,98,170,64,156,184,193,158,232,101,167,115,15,221,187,90,192,79,87,198,164,93,254,181,32,217,154,9,128,172,237,40,156,238,103,12,85,149,126,188,142,30,228,231,22,2,7,180,192,57,138,155,65,40,144,142,17,241,142,202,171,27,26,35,193,139,254,227,82,67,213,52,52,87,54,139,196,128,200,5,102,185,48,233,10,12,151,10,17,75,29,169,243,110,155,153,119,212,120,138,143,251,229,11,237,71,117,231,201.
        /// </summary>
        internal static string appid {
            get {
                return ResourceManager.GetString("appid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many clicks would you like? Please selection an option from the list below!.
        /// </summary>
        internal static string clicks {
            get {
                return ResourceManager.GetString("clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C 	 for Client.
        /// </summary>
        internal static string clientq {
            get {
                return ResourceManager.GetString("clientq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply us your email. address!.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to end.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach QCAT Licensing Servers. Please try agin later if this continues to happen please contact QCAT support.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit. Goodbye!.
        /// </summary>
        internal static string exitmagic {
            get {
                return ResourceManager.GetString("exitmagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating licence file....
        /// </summary>
        internal static string genlicxfile {
            get {
                return ResourceManager.GetString("genlicxfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I 	 for Isolator.
        /// </summary>
        internal static string isolatorq {
            get {
                return ResourceManager.GetString("isolatorq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K 	 for Koder.
        /// </summary>
        internal static string koderq {
            get {
                return ResourceManager.GetString("koderq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What licence type would you like?.
        /// </summary>
        internal static string licxtypequestion {
            get {
                return ResourceManager.GetString("licxtypequestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply your account password!.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string Program_GenerateLicenceFile__0____1__ {
            get {
                return ResourceManager.GetString("Program_GenerateLicenceFile__0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string Program_HowManyClicksDoYouWant_ {
            get {
                return ResourceManager.GetString("Program_HowManyClicksDoYouWant_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------.
        /// </summary>
        internal static string Program_Main_ {
            get {
                return ResourceManager.GetString("Program_Main_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the QCAT ODES Licence request program.
        /// </summary>
        internal static string Program_Main_Welcome_to_the_QCAT_ODES_Licence_request_program {
            get {
                return ResourceManager.GetString("Program_Main_Welcome_to_the_QCAT_ODES_Licence_request_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished saving licence request file to : {0}.
        /// </summary>
        internal static string savelicx {
            get {
                return ResourceManager.GetString("savelicx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your service queue name for the {0}!.
        /// </summary>
        internal static string servicequeue {
            get {
                return ResourceManager.GetString("servicequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	.
        /// </summary>
        internal static string tab {
            get {
                return ResourceManager.GetString("tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait....
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
    }
}
