//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickBox.CreateAccounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickBox.CreateAccounts.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;float:left;&quot;&gt;&lt;img src=&quot;cid:qcatlogo&quot; style=&quot;height:100px;&quot; /&gt;&lt;/div&gt;
        ///&lt;div style=&quot;border-left:thick solid #8B4513; width:20px; float:left; height:220px;&quot;&gt;&lt;/div&gt;
        ///&lt;p  style=&quot;float:left;&quot;&gt;
        ///	&lt;div style=&quot;margin-top:10px;&quot;&gt;{{welcome}}&lt;/div&gt;
        ///	&lt;div style=&quot;margin-top:10px;&quot;&gt;{{instructions}}&lt;/div&gt;
        ///	&lt;div style=&quot;margin-top:10px;&quot;&gt;
        ///		&lt;a href=&quot;{{downloadlink}}&quot;&gt;{{downloadlink}}&lt;/a&gt;
        ///	&lt;/div&gt;
        ///	&lt;div style=&quot;margin-top:30px;&quot;&gt;&lt;strong&gt;License Name: &lt;/strong&gt;&lt;span&gt;{{licenseName}}&lt;/span&gt;&lt;/div&gt;
        ///	&lt;div&gt;&lt;strong&gt;Pas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrialSuccessHtml {
            get {
                return ResourceManager.GetString("TrialSuccessHtml", resourceCulture);
            }
        }
    }
}
